!*********************************************************!
!*****        DISCONTINUOUS GALERKIN SOLVER       ********!
!*****                  FOR                        *******!
!*****             1D R13-EQUATIONS                   ****!
!*****                 *******                     *******!
!*****         DEVELOPER:   SATYVIR SINGH          *******!
!*********************************************************!
    
!***************************************************************** FIND PRIMITIVE
SUBROUTINE CONSERVATIVE_TO_PRIMITIVE(CONS_VAR,RHO_VAL,U_VAL,P_VAL,SIGMA_VAL,Q_VAL,T_VAL,ASOUND_VAL)
USE VARIABLES_INFO
IMPLICIT NONE
DOUBLE PRECISION,INTENT(IN):: CONS_VAR(MAX_EQ)
DOUBLE PRECISION,INTENT(OUT):: RHO_VAL
DOUBLE PRECISION,INTENT(OUT):: P_VAL
DOUBLE PRECISION,INTENT(OUT):: T_VAL
DOUBLE PRECISION,INTENT(OUT):: U_VAL
DOUBLE PRECISION,INTENT(OUT):: SIGMA_VAL
DOUBLE PRECISION,INTENT(OUT):: Q_VAL
DOUBLE PRECISION,INTENT(OUT):: ASOUND_VAL

RHO_VAL = CONS_VAR(1)
U_VAL   = CONS_VAR(2)/CONS_VAR(1)
P_VAL = (1.0/3.0)*(CONS_VAR(3) - RHO_VAL*U_VAL*U_VAL)
SIGMA_VAL = CONS_VAR(4) - RHO_VAL*U_VAL*U_VAL - P_VAL
Q_VAL =(1.0/2.0)*(CONS_VAR(5) - RHO_VAL*U_VAL**3 -5.0*P_VAL*U_VAL - 2.0*SIGMA_VAL*U_VAL)

IF(P_VAL.LT.0.0)THEN
    WRITE(*,*)"WARNING: PRESSURE BECOMES NEGATIVE !!!"
    STOP
END IF

T_VAL=P_VAL/(RHO_VAL*GASR)
ASOUND_VAL=2.0*SQRT(1.667*P_VAL/RHO_VAL)

END SUBROUTINE
    
    
!********************** FIND CONSERVATIVE
!********************** FIND CONSERVATIVE
SUBROUTINE PRIMARY_TO_CONSERVATIVE(RHO_VAL,U_VAL,P_VAL,SIGMA_VAL,Q_VAL,CONS_VAR)
USE VARIABLES_INFO
IMPLICIT NONE
DOUBLE PRECISION,INTENT(IN):: RHO_VAL
DOUBLE PRECISION,INTENT(IN):: P_VAL
DOUBLE PRECISION,INTENT(IN):: U_VAL
DOUBLE PRECISION,INTENT(IN):: SIGMA_VAL
DOUBLE PRECISION,INTENT(IN):: Q_VAL
DOUBLE PRECISION,INTENT(OUT):: CONS_VAR(MAX_EQ)

CONS_VAR(1)=RHO_VAL
CONS_VAR(2)=RHO_VAL*U_VAL
CONS_VAR(3)= RHO_VAL*U_VAL*U_VAL + 3.0*P_VAL
CONS_VAR(4)= RHO_VAL*U_VAL*U_VAL + P_VAL + SIGMA_VAL 
CONS_VAR(5)= RHO_VAL*U_VAL**3 + 5.0*P_VAL*U_VAL + 2.0*SIGMA_VAL*U_VAL + 2.0*Q_VAL


END SUBROUTINE
    