!*********************************************************!
!*****        DISCONTINUOUS GALERKIN SOLVER       ********!
!*****                  FOR                        *******!
!*****             1D R13-EQUATIONS                   ****!
!*****                 *******                     *******!
!*****         DEVELOPER:   SATYVIR SINGH          *******!
!*********************************************************!
    
MODULE VARIABLES_INFO
IMPLICIT NONE


INTEGER :: MAX_EQ
DOUBLE PRECISION,PARAMETER :: PI =2.0*ACOS(0.0)

!================================================================
! GOVERNING EQUATIONS
!================================================================
CHARACTER(LEN=40):: GOV_EQUATION_SWITCH
CHARACTER(LEN=40):: PROBLEM_SWITCH
CHARACTER(LEN=40):: BASIS_TYPE
CHARACTER(LEN=40):: TEMPORAL_SCHEME_SWITCH
CHARACTER(LEN=40):: INVISCID_FLUX_SWITCH
CHARACTER(LEN=40):: POSITIVE_LIMITER_SWITCH

!================================================================
! DOMAIN INFORMATION
!================================================================
INTEGER :: NELEM_X
DOUBLE PRECISION :: X_MIN, X_MAX
DOUBLE PRECISION :: DIAPHRAGM
DOUBLE PRECISION :: DOMAIN_SIZE
DOUBLE PRECISION :: UNIFORM_SPILITER
DOUBLE PRECISION :: MID_LINE,JACOBIAN_VALUE
DOUBLE PRECISION,ALLOCATABLE :: NODE_POS(:,:)
DOUBLE PRECISION,ALLOCATABLE :: DELTA_X(:)
DOUBLE PRECISION,ALLOCATABLE :: CENTER(:)
DOUBLE PRECISION,ALLOCATABLE :: JACOBIAN(:)

!================================================================
! GAS PROPERTIES
!================================================================
DOUBLE PRECISION :: GAMMA
DOUBLE PRECISION :: GASR
DOUBLE PRECISION :: PRODUCTION_B


!================================================================
! DG INFORMATION
!================================================================
INTEGER :: DG_ORDER
INTEGER :: MAX_BASIS

INTEGER :: MAX_VPOINTS
DOUBLE PRECISION,ALLOCATABLE :: V_POINT(:)
DOUBLE PRECISION,ALLOCATABLE :: V_WEIGHT(:)

DOUBLE PRECISION,ALLOCATABLE:: BASIS_VPOINT_INSIDE(:,:)
DOUBLE PRECISION,ALLOCATABLE:: BASIS_DER_VPOINT_INSIDE(:,:)
DOUBLE PRECISION,ALLOCATABLE:: BASIS_VPOINT_CENTER(:)
DOUBLE PRECISION,ALLOCATABLE:: BASIS_VP_FACE(:,:)
DOUBLE PRECISION,ALLOCATABLE:: INTEGRAL_BiBj_INVERSE(:,:)

DOUBLE PRECISION,ALLOCATABLE:: ai_CONSERVATIVE(:,:,:)
DOUBLE PRECISION,ALLOCATABLE:: ai_CONSERVATIVE_Old(:,:,:)
DOUBLE PRECISION,ALLOCATABLE:: Lu_CONSERVATIVE(:,:,:)
DOUBLE PRECISION,ALLOCATABLE:: ai_CONSERVATIVE_TVDSTEP(:,:,:,:)

DOUBLE PRECISION,ALLOCATABLE:: VOLUME_INTEGRAL_CONSERVATIVE(:,:,:)
DOUBLE PRECISION,ALLOCATABLE:: SURFACE_INTEGRAL_CONSERVATIVE(:,:,:)
DOUBLE PRECISION,ALLOCATABLE:: SOURCE_INTEGRAL_CONSERVATIVE(:,:,:)

DOUBLE PRECISION,ALLOCATABLE:: FLUX_FACES_X(:,:)

!================================================================
! STABILITY INFROMATION
!================================================================
INTEGER :: NPRINT
INTEGER :: ITERATION
INTEGER :: MAX_ITERATION
DOUBLE PRECISION :: CFL_NUMBER
DOUBLE PRECISION :: MINIMUM_DT
DOUBLE PRECISION :: FINAL_TIME
DOUBLE PRECISION :: CURRENT_TIME
DOUBLE PRECISION :: MAX_ERROR_VAL
DOUBLE PRECISION,ALLOCATABLE :: DT(:)
DOUBLE PRECISION :: ERROR_STATUS
DOUBLE PRECISION :: ERROR_LIMIT
DOUBLE PRECISION:: CURRENT_ERROR     
DOUBLE PRECISION:: MAX_RESIDUAL 


!================================================================
! ERROR INFORMATION
!================================================================
DOUBLE PRECISION,ALLOCATABLE:: L0_ERROR(:) 
DOUBLE PRECISION,ALLOCATABLE:: L1_ERROR(:) 
DOUBLE PRECISION,ALLOCATABLE:: L2_ERROR(:)

!================================================================
! FILE INFORMATION
!================================================================
CHARACTER(LEN=40):: DIRECTORY_1
CHARACTER(LEN=40):: DIRECTORY_2
CHARACTER(LEN=40):: DIRECTORY_3
CHARACTER(LEN=40):: DIRECTORY_4
CHARACTER(LEN=40):: DIRECTORY_5
CHARACTER(LEN=40):: FILE_NAME
CHARACTER(LEN=40):: FILENAME
CHARACTER(LEN=40):: INPUT_FILENAME
CHARACTER(LEN=40):: SUFFIX1
CHARACTER(LEN=40):: SUFFIX2
CHARACTER(LEN=40):: SUFFIX3
CHARACTER(LEN=40):: RESULTYPE

LOGICAL :: FINAL_SOLUTION = .FALSE. 

!************* TIME PROFILING
INTEGER ::STIME(8),FTIME(8)
DOUBLE PRECISION:: STARTtime
DOUBLE PRECISION:: FINALtime
DOUBLE PRECISION:: DIFFtime 
DOUBLE PRECISION:: CPUtime,TOTALtime



END MODULE