!*********************************************************!
!*****        DISCONTINUOUS GALERKIN SOLVER       ********!
!*****                  FOR                        *******!
!*****             1D R13-EQUATIONS                   ****!
!*****                 *******                     *******!
!*****         DEVELOPER:   SATYVIR SINGH          *******!
!*********************************************************!
    
SUBROUTINE DG_NUMERICAL_FLUX(W0_LEFT,W0_RIGHT,FLUX_SPLITTED)
USE VARIABLES_INFO
IMPLICIT NONE
DOUBLE PRECISION,INTENT(IN) :: W0_LEFT(MAX_EQ)
DOUBLE PRECISION,INTENT(IN) :: W0_RIGHT(MAX_EQ)
DOUBLE PRECISION,INTENT(OUT):: FLUX_SPLITTED(MAX_EQ)
DOUBLE PRECISION :: INV_FLUX_LEFT (MAX_EQ)
DOUBLE PRECISION :: INV_FLUX_RIGHT(MAX_EQ)
DOUBLE PRECISION :: DISSIPATION_TERM

IF(INVISCID_FLUX_SWITCH.EQ."LAX" )THEN
!        CALL LaxFriedrichs(W0_LEFT,W0_RIGHT,ELEMENT(N)%DT,ELEMENT(N)%DELTA_X,FLUX_SPLITTED)

ELSEIF(INVISCID_FLUX_SWITCH.EQ."RUSANOV" )THEN
        CALL RUSANOV_SCHEME(W0_LEFT,W0_RIGHT,FLUX_SPLITTED)

ELSEIF(INVISCID_FLUX_SWITCH.EQ."RICHTMYER" )THEN
!        CALL Richtmyer(W0_LEFT,W0_RIGHT,ELEMENT(N)%DT,ELEMENT(N)%DELTA_X,FLUX_SPLITTED)

ELSEIF(INVISCID_FLUX_SWITCH.EQ."MAC_CORMACK" )THEN
!        CALL MAC_CORMACK(W0_LEFT,W0_RIGHT,ELEMENT(N)%DT,ELEMENT(N)%DELTA_X,FLUX_SPLITTED)

ELSEIF(INVISCID_FLUX_SWITCH.EQ."STEGER_WARMING" )THEN
!        CALL StegerWarming(W0_LEFT,W0_RIGHT,FLUX_SPLITTED)

ELSEIF(INVISCID_FLUX_SWITCH.EQ."VAN_LEER" )THEN
!        CALL VanLeer(W0_LEFT,W0_RIGHT,FLUX_SPLITTED)

ELSEIF(INVISCID_FLUX_SWITCH.EQ."AUSM" )THEN
!        CALL AUSM(W0_LEFT,W0_RIGHT,FLUX_SPLITTED)

ELSEIF(INVISCID_FLUX_SWITCH.EQ."ZHA_BILGEN" )THEN
!        CALL ZhaBilgen(W0_LEFT,W0_RIGHT,FLUX_SPLITTED)

ELSEIF(INVISCID_FLUX_SWITCH.EQ."OSHER" )THEN
!        CALL Osher(W0_LEFT,W0_RIGHT,FLUX_SPLITTED)

ELSEIF(INVISCID_FLUX_SWITCH.EQ."ROE" )THEN
!        CALL ROE_OPT_FLUX_SPLITTING(W0_LEFT,W0_RIGHT,FLUX_SPLITTED)

ELSEIF(INVISCID_FLUX_SWITCH.EQ."HLL" )THEN
!        CALL HLL(W0_LEFT,W0_RIGHT,FLUX_SPLITTED)

ELSEIF(INVISCID_FLUX_SWITCH.EQ."HLLL" )THEN
!        CALL HLLL(W0_LEFT,W0_RIGHT,FLUX_SPLITTED)

ELSEIF(INVISCID_FLUX_SWITCH.EQ."AUFS" )THEN
!        CALL AUFS(W0_LEFT,W0_RIGHT,FLUX_SPLITTED)

ELSEIF(INVISCID_FLUX_SWITCH.EQ."GODUNOV" )THEN
!        CALL Godunov(W0_LEFT,W0_RIGHT,FLUX_SPLITTED)
ELSE
    WRITE(*,*)"ERROR, THIS KIND OF FLUX DOES NOT DEFINED IN THIS PROGRAM"
    STOP
END IF

END SUBROUTINE
