!*********************************************************!
!*****        DISCONTINUOUS GALERKIN SOLVER       ********!
!*****                  FOR                        *******!
!*****             1D R13-EQUATIONS                   ****!
!*****                 *******                     *******!
!*****         DEVELOPER:   SATYVIR SINGH          *******!
!*********************************************************!
    
SUBROUTINE RUSANOV_SCHEME(W0_LEFT,W0_RIGHT,FLUX)
USE VARIABLES_INFO
IMPLICIT NONE
DOUBLE PRECISION,INTENT(IN)  :: W0_LEFT(MAX_EQ)
DOUBLE PRECISION,INTENT(IN)  :: W0_RIGHT(MAX_EQ)
DOUBLE PRECISION,INTENT(OUT) :: FLUX(MAX_EQ)
DOUBLE PRECISION:: ALPHA_L,ALPHA_R,ALPHA
DOUBLE PRECISION:: RHOL,UL,PL,SIGMAL,QL,TL,AL
DOUBLE PRECISION:: RHOR,UR,PR,SIGMAR,QR,TR,AR
DOUBLE PRECISION:: INV_FLUX_LEFT(MAX_EQ)
DOUBLE PRECISION:: INV_FLUX_RIGHT(MAX_EQ)
INTEGER :: I

CALL CONSERVATIVE_TO_PRIMITIVE(W0_LEFT,RHOL,UL,PL,SIGMAL,QL,TL,AL)  
CALL CONSERVATIVE_TO_PRIMITIVE(W0_RIGHT,RHOR,UR,PR,SIGMAR,QR,TR,AR)

ALPHA_L = ABS( UL ) + AL 
ALPHA_R = ABS( UR ) + AR 
ALPHA   = MAX( ABS(ALPHA_L) , ABS(ALPHA_R) )

CALL PHYSICAL_FLUX (W0_LEFT,INV_FLUX_LEFT  )
CALL PHYSICAL_FLUX (W0_RIGHT,INV_FLUX_RIGHT)
DO I =1,MAX_EQ
FLUX(I) = 0.5*( (INV_FLUX_RIGHT(I) + INV_FLUX_LEFT(I)) -ALPHA*(W0_RIGHT(I) - W0_LEFT(I)) )
END DO

END SUBROUTINE
